config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users
  root 'static_pages#index'
  mount TalkingStick::Engine, at: '/talking_stick'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :meetings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	def render_not_found(status=:not_found)
    	render plain: "#{status.to_s.titleize} :(", status: status
  	end

  	protected
  	def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
  def after_sign_in_path_for(resource)
	stored_location_for(resource) || meetings_path
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = current_user.meetings.order('start_time').page(params[:page]).per_page(6)
    @allMeetings = Meeting.all
    @calTabActive = (params[:tab] == "calendar")
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user_id = current_user.id
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, :user_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def readable_time(time)
        time.strftime("%m/%d/%Y, %I:%M%P")
    end
    def display_day(day)
        time.strftime("%d")
    end
    def readable_month(time)
        time.strftime("%b")
    end
    def readable_dayofmonth(time)
        time.strftime("%d")
    end
    def readable_endTime(time)
        time.strftime("%I:%M%P")
    end
    def readable_startTime(time)
        time.strftime("%I:%M%P")
    end
    def readable_week(time)
        time.strftime("%A")
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_comment.html.erb
<div class="flex items-start p-4 mt-4 border rounded">
  <div class="flex-1 pl-4 flex items-start justify-between">
    <div class="leading-normal">
      <p class="text-grey-dark text-xs"><%= comment.user.username %> commented <%= time_ago_in_words(comment.created_at) %> ago</p>
      <div class="text-grey-darkest"><%= sanitize comment.reply %></div>
    </div>

    <% if author_of(comment) %>
      <%= link_to "Delete", meeting_comment_path(comment.meeting, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-destroy" %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<p class="text-sm text-grey-dark my-2">comment as <%= current_user.username %></p>

<%= form_for([@meeting, @comment], remote: true) do |f| %>
  <div class="relative">
    <%= f.hidden_field :reply, class: "input h-32 border border-grey-light resize-none", placeholder: "Add any notes or replies here" %>

    <trix-editor input="comment_reply" id="comment_reply_trix" class="h-32 p-4"></trix-editor>

    <%= f.submit class: "btn btn-small btn-secondary block w-full text-center mt-2 lg: mt-0 lg:text-left lg:absolute lg:pin-b lg:pin-r lg:mb-2 lg:mr-2 lg:w-auto lg:inline-flex" %>
  </div>
<% end %>

app/views/comments/create.js.erb
var comments = document.getElementById("comments");
var commentField = document.getElementById("comment_reply");
var trixField = document.getElementById("comment_reply_trix");
comments.insertAdjacentHTML("beforeend", "<%= escape_javascript(render(@comment)) %>");
commentField.value = "";
trixField.innerHTML = "";

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video Meeting App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'Video Meeting App', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Meetings', meetings_path, class: 'btn btn-primary' %>&nbsp;
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-primary' %>&nbsp;
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-danger' %>&nbsp;
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
         <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <!-- Error message if all fields are not filled out in new places form
    <% if flash[:error].present? %>
      <div class="col-10 offset-1 alert alert-danger">
        <%= flash[:error].html_safe %>
      </div>
    <% end %>-->

    <%= yield %>
   
    <div id="footer">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-9">
              <b>Meeting & Video App, All Rights Reserved &copy; 2019</b>
            </div>
          </div>
    </div>
  </div>
</body>
</html>

app/views/meetings/_calendar.html.erb
<%= month_calendar events: meetings do |date, meetings| %>
  <%= date %>
  <% meetings.each do |meeting| %>
    <div>
      <%= link_to meeting.name, meeting, class: "linkCal" %>
    </div>
  <% end %>
<% end %>

app/views/meetings/_form.html.erb
<div class="container col-md-5">
<div class="booyah-box d-flex justify-content-center">
<%= form_with(model: meeting, local: true, class: "meeting-form") do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h3 class="mb-4">Meeting Information</h3>
  <div class="mb-6">
    <%= form.label :Title, class: "form-group" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="mb-6">
    <%= form.label :start_time, class: "label" %>
    <div class="form-group">
      <%= form.datetime_select :start_time, { start_day: Date.today, start_year: Date.today.year, minute_step: 15 }, { class: "select" } %>
    </div>
  </div>
  <div class="field">
    <%= form.label :end_time, class: "label" %>
    <div class="form-group">
      <%= form.datetime_select :end_time, { start_day: Date.today, start_year: Date.today.year, minute_step: 15 }, { class: "select" } %>
    </div>
  </div>
  <hr class="border" />
  <%= form.submit class: "btn btn-primary text-base py-3 px-5" %>
<% end %>
</div>
</div>

app/views/meetings/_meetings_landing.html copy.erb
<nav class="bg-white mb-4 shadow rounded">
  <ul id="nav-tab" class="tabs list-reset flex">

    <li class="active" data-tab="calendar">
      <%= link_to "#calendar", class: "tab flex items-center" do %>
       <svg viewBox="0 0 20 20" width="16" height="16" class="fill-current text-grey-light mr-2"><title>calendar</title><path d="M1 4c0-1.1.9-2 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4zm2 2v12h14V6H3zm2-6h2v2H5V0zm8 0h2v2h-2V0zM5 9h2v2H5V9zm0 4h2v2H5v-2zm4-4h2v2H9V9zm0 4h2v2H9v-2zm4-4h2v2h-2V9zm0 4h2v2h-2v-2z"></path></svg>
       Calendar
      <% end %>
    </li>

     <li data-tab="all-meetings">
      <%= link_to "#all-meetings", class: "tab flex items-center" do %>
        <svg viewBox="0 0 20 20" class="fill-current text-grey-light mr-2" width="16" height="16"><title>coffee</title><path d="M4 11H2a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2h2V1h14v10a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4zm0-2V5H2v4h2zm-2 8v-1h18v1l-4 2H6l-4-2z"></path></svg>
      All Meetings
      <% end %>
    </li>

  </ul>
</nav>

<div class="bg-white p-10 border rounded">
  <div id="all-meetings" class="tab-panel">

     <h1>My Meetings</h1>

     <% meetings.each do |meeting| %>
        <div class="flex flex-wrap items-center justify-start p-4 border-b border-grey-light mb-6">
          <div class="flex-1 flex justify-between">
            <div>
              <%= link_to meeting.name, meeting, class: "link mr-4" %>
            </div>
            <div>
              <%= readable_time(meeting.start_time) %> &ndash;
              <%= readable_time(meeting.end_time) %>
            </div>
          </div>
        </div>

        <%= link_to "Cancel Meeting", meeting, method: :delete, data: { confirm: "Are you sure? There are no refunds." }, class: "btn btn-destroy ml-4" %>
     <% end %>
  </div>

  <div id="calendar" class="mtg_calendar tab-panel active">
    <div id="meeting-calendar">
      <%= render "calendar", meetings: meetings  %> 
    </div>
  </div>
</div>

app/views/meetings/_meetings_landing.html.erb
<br/>
<figure class="tabBlock">
  <ul class="tabBlock-tabs">
    <li class="tabBlock-tab <%= @calTabActive ? '' : 'is-active' %>">Meetings</li>
    <li class="tabBlock-tab <%= @calTabActive ? 'is-active' : '' %>">Calendar</li>
  </ul>
  <div class="tabBlock-content">
    <div class="tabBlock-pane">
    <div class="events-container">
        <span class="events__title">Upcoming events this month</span>
         <% meetings.each do |meeting| %>
        <ul class="events__list">
          <li class="events__item">
            <div class="events__item--left">
              <span class="events__name"><%= link_to meeting.name, meeting, class: "mr-4" %></span>
              <span class="events__date"><%= readable_time(meeting.start_time) %></span>
            </div>
            <span class="events__tag"><%= readable_startTime(meeting.start_time) %></span>
            <span class="events__tag"><%= readable_endTime(meeting.end_time) %></span>
            <%= link_to "Cancel Meeting", meeting, method: :delete, data: { confirm: "Are you sure? There are no refunds." }, class: "btn btn-destroy ml-4" %>
          </li>
        </ul>
        <% end %>
    </div>
  <div class="col-md-12 d-flex justify-content-center">
	    <%= will_paginate @meetings, previous_label: h("<"), next_label: h(">") %>
    </div>
    </div>
    <div class="tabBlock-pane">
      <div class="bg-white p-10 border rounded booyah-box">
      <h2 class="mtg_cal_title">Meeting Calendar</h2>
        <div id="calendar" class="mtg_calendar tab-panel active">
          <div id="meeting-calendar">
            <%= render "calendar", meetings: @allMeetings  %> 
          </div>
        </div>
      </div>
      </div>
  </div>
</figure>
<%= link_to "Schedule a Meeting", new_meeting_path, class: "btn btn-primary" %>
<script>
var TabBlock = {
  s: {
    animLen: 200
  },
  init: function() {
    TabBlock.bindUIActions();
    TabBlock.hideInactive();
  },
  bindUIActions: function() {
    $('.tabBlock-tabs').on('click', '.tabBlock-tab', function(){
      TabBlock.switchTab($(this));
    });
  },
  hideInactive: function() {
    var $tabBlocks = $('.tabBlock');
    $tabBlocks.each(function(i) {
      var 
        $tabBlock = $($tabBlocks[i]),
        $panes = $tabBlock.find('.tabBlock-pane'),
        $activeTab = $tabBlock.find('.tabBlock-tab.is-active');
      
      $panes.hide();
      $($panes[$activeTab.index()]).show();
    });
  },
  switchTab: function($tab) {
    var $context = $tab.closest('.tabBlock');
    if (!$tab.hasClass('is-active')) {
      $tab.siblings().removeClass('is-active');
      $tab.addClass('is-active');
      
      TabBlock.showPane($tab.index(), $context);
    }
   },
  showPane: function(i, $context) {
    var $panes = $context.find('.tabBlock-pane');
    $panes.slideUp(TabBlock.s.animLen);
    $($panes[i]).slideDown(TabBlock.s.animLen);
  }
};

$(function() {
  TabBlock.init();
});
</script>

app/views/meetings/_meetings_not_found.html.erb
<div class="max-w-md my-10 m-auto p-12 lg:p-16 bg-white rounded border border-grey-light text-center shadow">
  <%= image_tag "schedule.svg", alt: "schedule", width: 300, class: "mb-4" %>
  <h1 class="text-indigo-darker text-2xl mb-6">It looks like you haven't scheduled a session yet</h1>
  <%= link_to "Schedule a new session", new_meeting_path, class: "btn btn-primary py-3 px-5" %>
</div>

app/views/meetings/_payment_form.html.erb
<h3 class="pt-5 mb-4">Payment</h3>
  <div class="mb-6 relative mt-2">
    <label for="card-element" class="label">
      Enter credit or debit card. All sessions cost $199 USD.
    </label>

    <div id="card-element" class="input">
      <!-- a Stripe Element will be inserted here. -->
    </div>
    <!-- used to display Element errors -->
    <div id="card-errors" role="alert"></div>
  </div>

  
    <div class="bg-grey-lightest p-5 border border-grey-light rounded mb-6">
      <h4>Previously used card</h4>

      <div class="flex flex-wrap items-center justify-between my-4">
        <div class="w-full lg:w-auto mb-6 lg:mb-0">
          <p class="label">Card Brand</p>
        </div>
        <div class="w-full lg:w-auto mb-6 lg:mb-0">
          <p class="label">Last 4 Digits</p>
        </div>
        <div class="w-full lg:w-auto mb-6 lg:mb-0">
          <p class="label">Exp. Month</p>
        </div>
        <div class="w-full lg:w-auto">
          <p class="label">Exp. Year</p>
        </div>
      </div>
    </div>

app/views/meetings/active_sessions.html.erb
<div class="container m-auto bg-white my-10 border border-grey-light p-10">
  <h1 class="text-indigo-darker">Active Sessions</h1>

   <% @active_sessions.each do |meeting| %>
    <div class="flex flex-wrap items-center justify-start p-4 border-b border-grey-light mb-6">
      <div class="flex-1 flex justify-between">
        <div>
          <%= link_to meeting.name, meeting, class: "link mr-4" %>
        </div>
        <div>
          <%= readable_time(meeting.start_time) %> &ndash;
          <%= readable_time(meeting.end_time) %>
        </div>
      </div>

      <%= link_to 'Cancel Meeting', meeting, method: :delete, data: { confirm: 'Are you sure? There are no refunds' }, class: "btn btn-destroy ml-4" if admin? %>
    </div>
    <% end %>
</div>

app/views/meetings/edit.html.erb
<div class="max-w-lg m-auto px-4">
<div class="d-flex justify-content-center edit"><h1 class="text-3xl mt-10">Edit sessions</h1></div>
<div class="d-flex justify-content-center"><p class="text-lg text-grey-darker mb-6">Modify your consulting session by choosing the best time that works for you below.</p></div>
  <%= render 'form', meeting: @meeting %>
</div>

app/views/meetings/index.html.erb
<div class="container m-auto my-4">
  <% unless current_user.meetings.any? %>
    <%= render "meetings_not_found" %>
  <% else %>
    <%= render "meetings_landing", meetings: @meetings %>
  <% end %>
</div>

app/views/meetings/new.html.erb
<div class="max-w-lg m-auto px-4">
  <h1 class="text-center">Schedule a new session</h1>
  <p class="text-center">Schedule a new consulting session by choosing the best time that works for you below.</p>
  <%= render 'form', meeting: @meeting %>
</div>

app/views/meetings/show.html.erb
<div class="d-flex justify-content-center updateTitle"><h1>Update Meeting</h1></div>
<div class="container">
		<div class="row row-striped">
			<div class="col-2 text-right mtg_update_separator">
				<h1 class="display-4"><span class="badge-secondary"><%= readable_month(@meeting.start_time) %></span></h1>
				<h2><%= readable_dayofmonth(@meeting.start_time) %></h2>
			</div>
			<div class="col-10">
				<h3 class="text-uppercase"><strong><%= @meeting.name %></strong></h3>
				<ul class="list-inline">
					<li class="list-inline-item"><i class="fa fa-calendar-o" aria-hidden="true"></i>&nbsp;<%= readable_week(@meeting.start_time) %></li>
          <li class="list-inline-item"><i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;<%= readable_time(@meeting.start_time) %>-<%= readable_endTime(@meeting.end_time) %></li> 
        </ul>
        <h4>Comments</h4>
        <hr class="border" />
        <div class="text-center">
          <p class="text-sm"><%= link_to ('<button class="btn btn-primary videobtn"><i class="fa fa-video-camera">Video Consultation</i></button>').html_safe, talking_stick.rooms_path, class: "video_link" %></p>
        </div>
        <% unless user_signed_in? %>
          <div class="bg-grey-lighter rounded p-4 mt-4 text-center">
            <p class="text-sm text-grey-dark"><%= link_to "Login", new_user_session_path, class: "link" %> or <%= link_to "Sign up", new_user_regsitration_path, class: "link" %> to comment.</p>
          </div>
        <% end %>    
        <p class="editbtn"><%= link_to "Edit", edit_meeting_path(@meeting), class: "btn btn-primary" %></p>
				<p class="deletebtn"> <%= link_to "Cancel Meeting", meeting_path(@meeting), method: :delete, data: { confirm: "Are you sure you want to cancel? "}, class: "btn btn-danger" %></p>
			</div>
		</div>
	</div>
  

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
  <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class:'fc-prev-button btn btn-primary' %>
  <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, class:'fc-next-button btn btn-primary' %>
  <div class="fc-center"><span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span></div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
  <%= link_to t('simple_calendar.previous', default: 'Previous'), "#{calendar.url_for_previous_view}&tab=calendar", class:'fc-prev-button btn btn-primary' %>
    <%= link_to t('simple_calendar.next', default: 'Next'), "#{calendar.url_for_next_view}&tab=calendar", class:'fc-next-button btn btn-primary' %>
    <div class="fc-center"><span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span></div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
                <span class="text-sm text-gray-darker"><% block.call day.strftime("%d"), sorted_events.fetch(day, []) %></span>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/static_pages/index.html.erb
<!--Banner-->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
       <%= image_tag 'elearning.png', class: 'd-block img-fluid' %>
        <div class="carousel-caption d-none d-md-block">
          <h3>Start a Video Meeting</h3>
          <%= link_to 'Start Today!', new_user_registration_path, class: 'btn btn-danger' %>
         
       </div>
    </div>
  </div>
</div>
<!-- End of Banner-->

<br />
<div class="row feature text-center">
  <div class="col-12 col-sm">
    <i class="fa fa-youtube-play fa-4x icon"></i>
    <h3>Video Consultations</h3>
    <br />
    <p>Create meetings and video consultations</p>
  </div>

  <div class="col-12 col-sm">
    <i class="fa fa-tv fa-4x icon"></i>
    <h3>Schedule at Anytime</h3>
    <br />
    <p>Create an appointment today with a friend and keep track of your schedule</p>
  </div>

  <div class="col-12 col-sm">
    <i class="fa fa-code fa-4x icon"></i>
    <h3>Join our Community</h3>
    <br />
    <p>Connect and join our community</p>
  </div>
</div>

app/views/talking_stick/participants/_form.html.erb
<%= form_for([@room, @participant], path: talking_stick.room_participant_path(@room, @participant)) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/talking_stick/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form' %>

<%= link_to 'Show', [@room, @participant] %> |
<%= link_to 'Back', talking_stick.room_participants_path %>

app/views/talking_stick/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Participants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.name %></td>
        <td><%= participant.ip %></td>
        <td><%= link_to 'Show', [@room, participant] %></td>
        <td><%= link_to 'Edit', talking_stick.edit_room_participant_path(@room, participant) %></td>
        <td><%= link_to 'Destroy', [@room, participant], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', talking_stick.new_room_participant_path(@room) %>